# base info
baseURL: 'https://blog.dsrkafuu.net'

# features
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
taxonomies:
  tag: 'tags'
paginate: 10
disableKinds:
  - 'RSS'
enableGitInfo: true
frontmatter:
  lastmod:
    - :git
    - :fileModTime
    - :default

# params
params:
  mainSections:
    - 'post'
    - 'code'

# menu
menu:
  main:
    - name: '文章'
      url: '/post/'
      weight: 1
    - name: '笔记'
      url: '/code/'
      weight: 2
    - name: '标签'
      url: '/tags/'
      weight: 3
    - name: '友链'
      url: '/friends/'
      weight: 4
    - name: '番剧'
      url: '/playlist/'
      weight: 5
  links:
    - name: 'github'
      url: 'https://github.com/dsrkafuu'
      weight: 1
    - name: 'twitter'
      url: 'https://twitter.com/dsrkafuu'
      weight: 2
    - name: 'steam'
      url: 'https://steamcommunity.com/id/dsrkafuu/'
      weight: 3

# markup
markup:
  goldmark:
    renderer:
      unsafe: true # enable user-embed HTML snippets
  highlight:
    codeFences: false # disable code highlighter
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 3

# do not generate jsconfig
build:
  noJSConfigInAssets: true

# security settings
security:
  enableInlineShortcodes: true
  funcs:
    getenv: '^(HUGO_|NODE_ENV)'
