# base info
baseURL: "https://amzrk2.cc/"
title: "DSRKafuU"

# features
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
taxonomies:
  tag: tags

# language
languageCode: "zh-cn" # rss
defaultContentLanguage: "zh-hans" # html

params:
  author: "DSRKafuU"
