# base info
baseURL: 'https://blog.dsrkafuu.net'

# features
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
paginate: 10
enableGitInfo: true
frontmatter:
  lastmod:
    - :git
    - :fileModTime
    - :default
disableKinds:
  - 'taxonomy'
  - 'term'

# only preserve home rss
outputs:
  page:
    - HTML
  home:
    - HTML
    - RSS
  section:
    - HTML

# params
params:
  mainSections:
    - 'post'
    - 'code'
  giscusRepo: 'dsrkafuu/dsr-blog'
  giscusRepoID: 'MDEwOlJlcG9zaXRvcnkyODcyODY2NjE='
  giscusCatg: '评论'
  giscusCatgID: 'DIC_kwDOER-lhc4CO7Hv'
  giscusFriendsID: '5'

# menu
# https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
sectionPagesMenu: 'main'

# markup
markup:
  goldmark:
    renderer:
      unsafe: true # enable user-embed HTML snippets
  highlight:
    codeFences: false # disable code highlighter
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 3

# do not generate jsconfig
build:
  noJSConfigInAssets: true

# security settings
security:
  enableInlineShortcodes: true
  funcs:
    getenv: '^(HUGO_|NODE_ENV)'
